# Generated by Django 5.1.7 on 2025-03-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_cartao_nome_alter_cartao_saldo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'ordering': ['nome'], 'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AlterField(
            model_name='cartao',
            name='limite',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Apenas para cartões de crédito', max_digits=10, null=True, verbose_name='Limite (R$)'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='nome',
            field=models.CharField(help_text='Ex: Nubank, Itaú, etc.', max_length=100, verbose_name='Nome do Cartão'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Apenas para cartões de débito', max_digits=10, null=True, verbose_name='Saldo (R$)'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='tipo',
            field=models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10, verbose_name='Tipo de Cartão'),
        ),
    ]
